export type Account={name:string;siteUrl:string;username:string;appPassword:string;passwordFile:string};
export type Config={accounts:Account[];defaultAccount:string;readOnly:boolean;allowDestructive:boolean;auditPath:string;timeoutMs:number;minIntervalMs:number};
function integer(v:string|undefined,fallback:number,min:number,max:number){const n=v?Number(v):fallback;if(!Number.isInteger(n)||n<min||n>max)throw Error('Invalid request timeout or pacing settings.');return n;}
export function normalizeSite(value:string){let u:URL;try{u=new URL(value);}catch{throw Error('Private Fluent WordPress profile requires a valid HTTPS site URL.');}if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||/[\\\x00-\x1f]/.test(value)||/%2f|%5c|%00|%2e/i.test(value)||value.split('/').some(p=>p==='.'||p==='..')||/\/wp-json(?:\/|$)/.test(u.pathname))throw Error('Use a trusted HTTPS WordPress site root, with an optional install subdirectory; no credentials/query/fragment/wp-json or traversal.');return u.origin+u.pathname.replace(/\/+$/,'');}
function alias(env:NodeJS.ProcessEnv,canonical:string,legacy:string){if(env[canonical]&&env[legacy]&&env[canonical]!==env[legacy])throw Error('Conflicting private Fluent WordPress legacy/canonical settings.');return env[canonical]||env[legacy];}
export function loadConfig(env:NodeJS.ProcessEnv=process.env):Config{
 let entries:Record<string,unknown>[]=[];
 if(env.FLUENT_WP_ACCOUNTS){try{const a=JSON.parse(env.FLUENT_WP_ACCOUNTS);if(!Array.isArray(a))throw Error();entries=a;}catch{throw Error('FLUENT_WP_ACCOUNTS must be a private JSON array of named site profiles.');}}
 else{const site_url=alias(env,'FLUENT_WP_SITE_URL','FLUENT_WP_URL'),app_password=alias(env,'FLUENT_WP_APP_PASSWORD','FLUENT_WP_PASS');if(site_url||env.FLUENT_WP_USER||app_password||env.FLUENT_WP_PASSWORD_FILE)entries=[{name:'default',site_url,username:env.FLUENT_WP_USER,app_password,password_file:env.FLUENT_WP_PASSWORD_FILE}];}
 const accounts=entries.map(x=>{if(!x||typeof x!=='object'||typeof x.name!=='string'||!x.name.trim())throw Error('Every Fluent WordPress profile requires a unique nonempty name.');for(const k of ['site_url','username','app_password','password_file'])if(x[k]!==undefined&&(typeof x[k]!=='string'||/[\r\n\x00]/.test(x[k]as string)))throw Error('Private Fluent WordPress profile settings must be strings without line breaks.');if(!x.site_url||!x.username||String(x.username).includes(':')||!String(x.username).trim())throw Error('Private Fluent WordPress profile requires its own site_url and username.');if(x.app_password&&x.password_file)throw Error('Select a private inline application password or password_file, never both.');return{name:x.name.trim(),siteUrl:normalizeSite(String(x.site_url)),username:String(x.username),appPassword:String(x.app_password??''),passwordFile:String(x.password_file??'')};});
 if(new Set(accounts.map(a=>a.name)).size!==accounts.length)throw Error('Fluent WordPress profile names must be unique.');const defaultAccount=env.FLUENT_WP_DEFAULT_ACCOUNT??accounts[0]?.name??'';if(defaultAccount&&!accounts.some(a=>a.name===defaultAccount))throw Error('Unknown FLUENT_WP_DEFAULT_ACCOUNT.');
 return{accounts,defaultAccount,readOnly:/^(1|true)$/i.test(env.FLUENT_WP_READ_ONLY??''),allowDestructive:!/^(0|false)$/i.test(env.FLUENT_WP_ALLOW_DESTRUCTIVE??''),auditPath:env.FLUENT_WP_AUDIT_LOG??'',timeoutMs:integer(env.FLUENT_WP_REQUEST_TIMEOUT_MS,30000,100,300000),minIntervalMs:integer(env.FLUENT_WP_MIN_REQUEST_INTERVAL_MS,250,0,10000)};
}
export function selectAccount(c:Config,hint?:string){const a=c.accounts.find(a=>a.name===(hint??c.defaultAccount));if(!a)throw Error(c.accounts.length?'Unknown profile; run list_accounts and use its exact label.':'No credentials configured. Set FLUENT_WP_SITE_URL, FLUENT_WP_USER and a private application password/file; run fluent-wp-cli login.');return a;}
