import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{FluentWpClient,type Json,type QueryParam}from'../api/client.js';import{FluentWpError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type { Risk } from "@thenavidm/slipway";
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean;source:Json};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:FluentWpClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false,formats:{int64:true}});(addFormats as unknown as(a:Ajv)=>void)(ajv);

// Each schema compiles on first use: compiling all of them at load held back the server's first answer. compileAll() runs them in tests.
const bodyValidators=new Map<string,ValidateFunction>();function bodyValidator(op:Operation):ValidateFunction{let v=bodyValidators.get(op.name);if(!v){v=ajv.compile(op.bodySchema!);bodyValidators.set(op.name,v);}return v;}

function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));Object.assign(properties,op.bodySchema?.properties??{});properties.account={type:'string',description:'Exact configured private account profile label; not a tenant or provider account ID.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Must be true for the requested mutation or exclusive private output file.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native JSON body; do not mix with body flags or payload_file. Arrays use repeated JSON object flags or a whole native array in a private file.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink JSON body file, at most 1 MiB. Cannot mix with payload/body flags.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute new private file. Exclusive 0600 creation; never overwrites or echoes private native output.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON body file, at most 1 MiB.');}finally{await f?.close();}}
function semantics(op:Operation,args:Json,body:any){
 if(op.bodySchema&&(!body||typeof body!=='object'||!Object.keys(body).length))throw new UsageError('Provide a nonempty native request body.');
 if(body?.message!==undefined&&!body.message.trim()||body?.comment!==undefined&&!body.comment.trim())throw new UsageError('Native content cannot be blank.');
 for(const p of op.params){if(p.in==='path'){const v=String(args[p.key]??'');if(!v.trim()||/[\\/\x00-\x1f?#]/.test(v)||['.','..'].includes(v))throw new UsageError('Native path parameters cannot contain separators or traversal.');}}
 if(op.name==='ff_form_stats'&&(args.start_date!==undefined)!==(args.end_date!==undefined))throw new UsageError('Provide both native start_date and end_date, or neither.');
}
async function prepare(op:Operation,args:Json){const flat=Object.fromEntries(Object.keys(op.bodySchema?.properties??{}).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));if((args.payload!==undefined||args.payload_file!==undefined)&&Object.keys(flat).length)throw new UsageError('Do not mix body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');let body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??flat):undefined;if(op.bodyRequired&&args.payload===undefined&&!args.payload_file&&!Object.keys(flat).length)throw new UsageError('This operation requires a native body; inspect schema and provide body flags, payload or payload_file.');if(op.bodySchema)check(bodyValidator(op),body);semantics(op,args,body);const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));return{method:op.method,path,query,body};}
async function execute(op:Operation,args:Json,client:FluentWpClient){const call=await prepare(op,args);return client.sanitize(await client.request(call.method,call.path,call.query,call.body,args.account));}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact configured private site profile label, not a verified site-owner identity.'};const confirm={type:'boolean',description:'Explicit approval for this exact requested work or new private file.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('list_accounts','List configured sites','Local profile labels/default/credential source only; no site URL, username, password path, provider identity or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,credentialSource:a.passwordFile?'private_password_file':a.appPassword?'private_setting':'not_configured'}))}));
helper('get_operation_schema','Inspect a current native operation','Local method/path/query/body schema and pinned provenance for one selected native tool. No provider call or credentials.','read',{operation:{type:'string',enum:operations.map(o=>o.name),description:'Actual native tool name, including fc_update_feed and ff_list_submissions.'}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const analytics={'top-members':'fc_analytics_top_members','top-commenters':'fc_analytics_top_commenters','top-post-starters':'fc_analytics_top_post_starters','activity':'fc_analytics_member_activity'};
helper('fc_analytics_overview','Read one native Community member report','Retained legacy selector mapped to four fixed reviewed native Pro report routes. Not a whole-community analytics export; native report permissions apply.','read',{account,type:{type:'string',enum:Object.keys(analytics),description:'One native report, default top-members.'}},[],async(a,c)=>ALL_TOOLS.find(t=>t.name===analytics[(a.type??'top-members')as keyof typeof analytics])!.handler({account:a.account},c));
const readNames=operations.filter(o=>o.risk==='read').map(o=>o.name);const writeNames=operations.filter(o=>o.risk!=='read'&&o.method!=='GET').map(o=>o.name);
function taskSchema(names:string[]){return{type:'array',minItems:1,maxItems:20,description:'One to twenty exact ordered native requests. Each read is one native response/page; no automatic pagination, URL following, polling or cross-site override.',items:{type:'object',properties:{tool:{type:'string',enum:names},arguments:{type:'object',description:'Native arguments without account, confirm, payload_file or output_file; complete payload is allowed.'}},required:['tool','arguments'],additionalProperties:false}};}
const readTasks=taskSchema(readNames),writeTasks=taskSchema(writeNames);
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
async function reviewed(args:Json,c:FluentWpClient,allowed:string[]){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported site batch tool.');if(['account','confirm','payload_file','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override the selected site or confirmation, or reference mutable files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(await prepare(op,task.arguments));}return{version:1,profile:selected.name,siteUrl:selected.siteUrl,username:selected.username,snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_site_batch','Review exact ordered cross-plugin tasks','Local native validation/hash for 1–20 CRM/Community writes. Binds selected profile label/site/username, request order and packaged schemas. No password read/provider state check or remote approval token.','read',{tasks:writeTasks,account},['tasks'],async(a,c)=>{const r=await reviewed(a,c,writeNames);const{siteUrl,username,...display}=r;return{...c.sanitize(display)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Exact input review, not a state lock, credential-owner proof, cryptographic human approval, rollback guarantee or official Forms five-minute confirmation token.'};});
helper('submit_site_batch','Execute reviewed cross-plugin tasks','Confirmed 1–20 ordered CRM/Community writes. Validate every request and exact review hash before first request, stop on first failure with known receipts and unattempted indices; no retries/rollback/continuation.','destructive',{tasks:writeTasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_site_batch hash for unchanged tasks, site profile and schema.'}},['tasks','review_sha256'],async(a,c)=>{const r=await reviewed(a,c,writeNames);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview the exact selected site and tasks again.');const knownResults:Json[]=[];let total=0;for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));total+=Buffer.byteLength(JSON.stringify(result));if(total>5*1048576)throw new FluentWpError('Combined receipts exceed 5 MiB; the current request may already have changed state. Inspect provider state.');knownResults.push({index:i,tool:a.tasks[i].tool,result});}catch(e){const err=e as FluentWpError;throw new FluentWpError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request may have an unknown outcome or pending side effects. Inspect state before repeating. No retry or rollback.',knownResults,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{requestsReturned:true,knownResults,notice:'Native receipts returned; announcements, automations and hook side effects may continue separately.'};});
async function readSnapshot(args:Json,c:FluentWpClient,privateFile=false){const r=await reviewed(args,c,readNames);const responses:Json[]=[];let bytes=0;for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));bytes+=Buffer.byteLength(JSON.stringify(result));if(bytes>5*1048576)throw new FluentWpError('Combined native responses exceed 5 MiB. Narrow the requested tasks/pages.');responses.push({index:i,tool:args.tasks[i].tool,result});}catch(e){const err=e as FluentWpError;throw new FluentWpError(JSON.stringify({notice:'Snapshot stopped; no automatic retries, no remaining requests.',completedIndices:responses.map(r=>r.index),failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),...(privateFile?{privateResultsEchoed:false}:{error:err.message})}),err.status??0,err.code??'API_ERROR');}}return{profile:r.profile,snapshotSha256:r.snapshotSha256,singleResponses:true,atomicProviderSnapshot:false,responses};}
helper('read_site_snapshot','Read bounded cross-plugin responses','Prevalidate 1–20 native reads for one exact private site profile; return at most5 MiB combined CRM/Community/Forms responses. No auto-pages, stateful report, browser cookies, uploads or atomic provider snapshot. Native records may contain private personal data.','read',{tasks:readTasks,account},['tasks'],async(a,c)=>readSnapshot(a,c));
helper('save_site_snapshot','Save bounded cross-plugin responses privately','Confirmed 1–20 prevalidated native reads delivered only to an exclusive new0600 JSON file. No record body echoed, overwrites, upload or all-pages guarantee. Failures remove only this helper’s newly created file and return indices without native records.','destructive',{tasks:readTasks,account,confirm,output_file:{type:'string',minLength:1,description:'Absolute new file in an existing private directory; restrict Windows ACLs separately.'}},['tasks','output_file'],async(a,c)=>{if(!isAbsolute(a.output_file))throw new UsageError('output_file must be absolute.');await reviewed(a,c,readNames);let f;try{f=await open(a.output_file,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file.');}try{const data=await readSnapshot(a,c,true);const bytes=Buffer.from(JSON.stringify(data)+'\n');await f.writeFile(bytes);return{saved:true,output_file:a.output_file,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),nativeRecordsEchoed:false,atomicProviderSnapshot:false};}catch(e){await f.close();f=undefined;await unlink(a.output_file).catch(()=>{});throw e;}finally{await f?.close();}});
const validators=new Map<string,ValidateFunction>();function validatorFor(tool:ToolSpec):ValidateFunction{let v=validators.get(tool.name);if(!v){v=ajv.compile(tool.inputSchema);validators.set(tool.name,v);}return v;}export function validateArguments(tool:ToolSpec,args:Json){check(validatorFor(tool),args);}
/** Compile every input and body schema, as loading once did, so a test can prove they all compile. */
export function compileAll():number{for(const t of ALL_TOOLS)validatorFor(t);for(const o of operations)if(o.bodySchema)bodyValidator(o);return validators.size+bodyValidators.size;}
export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
